#on: [push]
name: Linux_ACI_SAMPLE_Workflow

jobs:
#    build-and-deploy:
#        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: acr67400psy.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t acr67400psy.azurecr.io/nodejssampleapp:${{ github.sha }}
            docker push acr67400psy.azurecr.io/nodejssampleapp:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: gr1
            dns-name-label: url-for-container
            image: acr67400psy.azurecr.io/nodejssampleapp:${{ github.sha }}
            cpu: 1   #Optional
            memory: 0.1   #Optional
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: sample-container
            location: 'east us'
